// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiyryjsbobducdplleer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpeXJ5anNib2JkdWNkcGxsZWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDQzMjcsImV4cCI6MjA1OTY4MDMyN30.Xf0YTnOfCerttdGFu9rbAWfkWTaEVnucFGO6CCYg6Es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);